# Generated by Django 5.0.6 on 2024-07-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('track_number', models.PositiveIntegerField()),
                ('album_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.album')),
            ],
        ),
    ]
